import './globals.css';
import {SessionProvider} from 'next-auth/react';
import {auth} from '@/auth';
import type {Metadata} from 'next';
import NavBar from '@/components/nav-bar';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode[];
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body>
          <div className="w-full h-full overflow-hidden flex flex-col">
            {
              session?.user ? <NavBar /> : null
            }
            <div className="grow">
              {children}
            </div>
          </div>
        </body>
      </html>

    </SessionProvider>
  )
  ;
}
